### PR TITLE
Fixing this in anonoymous class

### LINKED ISSUE #2467: `$this` not recognized inside anonymous class
Hello!

Please see the following:

```php
<?php

return new class
{
    public function foo(): void
    {
        $this->bar();
    }

    public function bar(): bool
    {
        return false;
    }
};
```

image

Thanks!

### PR DESCRIPTION
**Pull request by mamazu**
Fixes #2467

### CODE REVIEW

File: lib/WorseReflection/Core/Inference/Walker/FunctionLikeWalker.php [hunk 1]
```diff
@@ -71,7 +72,8 @@ private function walkFunctionLike(FrameResolver $resolver, Frame $frame, Functio
             ClassDeclaration::class,
             InterfaceDeclaration::class,
             TraitDeclaration::class,
-            EnumDeclaration::class
+            EnumDeclaration::class,
+            ObjectCreationExpression::class, // For Inline classes
```
Comment (dantleech) [inline lib/WorseReflection/Core/Inference/Walker/FunctionLikeWalker.php:76]: not sure this will work as object creation expressions can be inside class declarations etc.

Comment (mamazu) [reply lib/WorseReflection/Core/Inference/Walker/FunctionLikeWalker.php:76]: I have looked at the node tree. And where a normal definition has a ClassDefinitionNode there is an ObjectCreactionExpression

Comment (dantleech) [reply lib/WorseReflection/Core/Inference/Walker/FunctionLikeWalker.php:76]: ah i see, i'm confusing ancestor and descendant :facepalm:

**Comment by dantleech** [comment]
the next bit would probably be adding a new `AnonymousClassType` implementing `ClassLikeType`  and adding the class members to it, probably quite some work to do there.
