### PR TITLE
Gh 2366: Fix undefined var behavior for `@var` declarations

### LINKED ISSUE #2366: @var annotation behaving erratically
I have a PHP template file, which is included from my template engine class. Hence the variables are not defined within the template file, and I am trying to define the variables using @var annotation. But phpactor is behaving erratically when @var annotation is used to specify the type of a variable.

```
<?php

/** @var string $a */
/** @var string $b */
/** @var string $c */
?>
<?php

echo $a + $b;

echo $a;
echo $b;

```

image

But if I change the `+` operator to `.`, it no longer works.

image

### PR DESCRIPTION
**Pull request by dantleech**
Fixes #2366

### CODE REVIEW

File: lib/WorseReflection/Core/Inference/Resolver/BinaryExpressionResolver.php [hunk 1]
```diff
@@ -297,7 +297,6 @@ private function addVariable(
 
         if (!in_array($operator, [
             TokenKind::DotEqualsToken,
-            TokenKind::DotToken,
```
Comment (dantleech) [inline lib/WorseReflection/Core/Inference/Resolver/BinaryExpressionResolver.php:300]: there may well have been a reason for this, but it's lost in time and the tests don't care so :shrug:
