### PR TITLE
Gh 1516

### LINKED ISSUE #1516: Bugs in completion/go to inside docblock
Thanks for making phpdocs more alive ( https://github.com/phpactor/phpactor/issues/1507). Even in this version it can save us lot of time although it still requires some fixes.

Sometimes completion works as expected, sometimes (on `lib/Phpactor.php`) it still behaves in a strange way such as on the screencast https://asciinema.org/a/9mI44uwaDhfb1aDdPxntkRNBK (with `--stdin` but keystrokes are not shown unfortunately). 

Currently `Phpactor\Phpactor` has imported only `Resolver` class: `Phpactor\MapResolver\Resolver`. 
-please try to add virtual properties:
```php
/**
 * @property Resolver $resolver
 * @property Phpactor\MapResolver\Resolver $resolver2
 */
```
- try to go to both definitions (I cannot go to them)
- complete both the class names. On `Resolver` II get alias `AmpResolver` (`use Amp\Dns\Resolver as AmpResolver`). 
- if you'll get `AmpResolver` in effect, try to go to it. I can go to the incorrectly selected definition. 
- undo all changes and try to add a real property with type `Resolver` (for me it works as expected).

### PR DESCRIPTION
**Pull request by dantleech**
Fixes #1516

### CODE REVIEW

File: lib/WorseReferenceFinder/Tests/Unit/WorsePlainTextDefinitionLocatorTest.php [hunk 1]
```diff
@@ -74,6 +76,19 @@ class Ha {
...
+            namespace Barfoo;
+
+            use Baz\Boo;
+
+            /**
+             * @property B<>oo
+             */
+            class Baz {}
+            EOT
+        , 'Boo.php' ];
```
Comment (dantleech) [inline lib/WorseReferenceFinder/Tests/Unit/WorsePlainTextDefinitionLocatorTest.php:91]: note this test passes without the fix :thinking: oh well.
