### PR TITLE
[RPC] find references: Do not return files with no concrete reference…

### LINKED ISSUE #581: [emacs] risky references given as references when invoking file_references
Here are the replay logs and content of phpactor's output buffer in emacs

```
phpactor rpc --replay --verbose                                                                                                                     
[2018-08-27 07:52:40] phpactor.DEBUG: REQUEST {"action":"references","parameters":{"mode":"replace","filesystem":"git","replacement":"handle","source":"<?php\n\nnamespace AppBundle\\Application\\Forecast;\n\nuse AppBundle\\Entity\\Forecast;\nuse AppBundle\\Repository\\ForecastRepository;\n\nfinal class ForecastQualificationHandler\n{\n    /**\n     * @var ForecastRepository\n     */\n    private $forecastRepository;\n\n    /**\n     * @var ForecastCostHandler\n     */\n    private $forecastCostHandler;\n\n    public function __construct(\n        ForecastRepository $forecastRepository,\n        ForecastCostHandler $forecastCostHandler\n    ) {\n        $this->forecastRepository  = $forecastRepository;\n        $this->forecastCostHandler = $forecastCostHandler;\n    }\n\n    public function handle(ForecastQualificationCommand $command)\n    {\n        $forecast = $this->forecastRepository->get($command->getForecastId());\n\n        if (Forecast::QUALIFICATION_POSITIVE === $command->getQualification()) {\n            $forecast->qualifyPositive();\n            $this->forecastCostHandler->handle($forecast);\n        }
elseif (Forecast::QUALIFICATION_WITHOUT_RESULT === $command->getQualification()) {\n            $forecast->qualifyWithoutResult();\n        } elseif (Forecast::QUALIFICATION_AUTO_CLOSED === $command->getQualification()) {\n            $forecast->autoQualifyWithoutResult();\n            $this->forecastCostHandler->handleAutomaticWithoutResultQualification($forecast);\n        } else {\n            throw new \\LogicException();\n        }\n    }\n}\n","path":"/path/src/AppBundle/Application/Forecast/ForecastQualificationHandler.php","offset":712}} []        
[2018-08-27 07:52:40] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\Statement\ClassDeclaration [] []
[2018-08-27 07:52:40] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\Parameter [] []
[2018-08-27 07:52:40] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\Expression\CallExpression [] []
[2018-08-27 07:52:40] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\Expression\MemberAccessExpression [] []
[2018-08-27 07:52:40] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\Expression\MemberAccessExpression [] []
[2018-08-27 07:52:40] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\Expression\Variable [] []
[2018-08-27 07:52:40] phpactor.DEBUG: Resolved type "AppBundle\Repository\ForecastRepository" for property "forecastRepository" of class "AppBundle\Application\Forecast\ForecastQualificationHandler" [] []                                                                                          
[2018-08-27 07:52:40] phpactor.DEBUG: Resolved type "<unknown>" for method "get" of class "AppBundle\Repository\ForecastRepository" [] []
[2018-08-27 07:52:40] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\MethodDeclaration [] []
[2018-08-27 07:52:40] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\Statement\ClassDeclaration [] []
[2018-08-27 07:52:40] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\Statement\ClassDeclaration [] []
[2018-08-27 07:52:40] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\Parameter [] []
[2018-08-27 07:52:40] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\Expression\CallExpression [] []
[2018-08-27 07:52:40] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\Expression\MemberAccessExpression [] []
[2018-08-27 07:52:40] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\Expression\MemberAccessExpression [] []
[2018-08-27 07:52:40] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\Expression\Variable [] []
[2018-08-27 07:52:40] phpactor.DEBUG: Resolved type "AppBundle\Repository\ForecastRepository" for property "forecastRepository" of class "AppBundle\Application\Forecast\ForecastQualificationHandler" [] []                                                                                          
[2018-08-27 07:52:40] phpactor.DEBUG: Resolved type "<unknown>" for method "get" of class "AppBundle\Repository\ForecastRepository" [] []
[2018-08-27 07:52:40] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\Expression\MemberAccessExpression [] []
[2018-08-27 07:52:40] phpactor.DEBUG: Resolving: Microsoft\PhpParser\Node\Expression\Variable [] []
[2018-08-27 07:52:40] phpactor.DEBUG: Resolved type "AppBundle\Application\Forecast\ForecastCostHandler" for property "forecastCostHandler" of class "AppBundle\Application\Forecast\ForecastQualificationHandler" [] []                                                                        
[2018-08-27 07:52:40] phpactor.DEBUG: RESPONSE {"action":"echo","parameters":{"message":"No references found"}} []
{"action":"echo","parameters":{"message":"No references found"}}%                                    
```

output

```json
{
  "action": "collection",
  "parameters": {
    "actions": [
      {
        "name": "echo",
        "parameters": {
          "message": "Replaced 1 literal references to method \"handle\" using FS \"git\" (9 risky references not listed)"
        }
      },
      {
        "name": "update_file_source",
        "parameters": {
          "path": "/path/src/AppBundle/Application/Forecast/ForecastQualificationHandler.php",
          "source": "<?php\n\nnamespace AppBundle\\Application\\Forecast;\n\nuse AppBundle\\Entity\\Forecast;\nuse AppBundle\\Repository\\ForecastRepository;\n\nfinal class ForecastQualificationHandler\n{\n    /**\n     * @var ForecastRepository\n     */\n    private $forecastRepository;\n\n    /**\n     * @var ForecastCostHandler\n     */\n    private $forecastCostHandler;\n\n    public function __construct(\n        ForecastRepository $forecastRepository,\n        ForecastCostHandler $forecastCostHandler\n    ) {\n        $this->forecastRepository  = $forecastRepository;\n        $this->forecastCostHandler = $forecastCostHandler;\n    }\n\n    public function handle2(ForecastQualificationCommand $command)\n    {\n        $forecast = $this->forecastRepository->get($command->getForecastId());\n\n        if (Forecast::QUALIFICATION_POSITIVE === $command->getQualification()) {\n            $forecast->qualifyPositive();\n            $this->forecastCostHandler->handle($forecast);\n        } elseif (Forecast::QUALIFICATION_WITHOUT_RESULT === $command->getQualification()) {\n            $forecast->qualifyWithoutResult();\n        } elseif (Forecast::QUALIFICATION_AUTO_CLOSED === $command->getQualification()) {\n            $forecast->autoQualifyWithoutResult();\n            $this->forecastCostHandler->handleAutomaticWithoutResultQualification($forecast);\n        } else {\n            throw new \\LogicException();\n        }\n    }\n}\n",
          "edits": [
            {
              "start": {
                "line": 27,
                "character": 0
              },
              "end": {
                "line": 28,
                "character": 0
              },
              "text": ""
            },
            {
              "start": {
                "line": 27,
                "character": 0
              },
              "end": {
                "line": 27,
                "character": 0
              },
              "text": "    public function handle2(ForecastQualificationCommand $command)\n"
            }
          ]
        }
      },
      {
        "name": "file_references",
        "parameters": {
          "file_references": [
            {
              "file": "/path/features/bootstrap/SpotContext.php",
              "references": []
            },
            {
              "file": "/path/src/AppBundle/Application/Forecast/ForecastQualificationHandler.php",
              "references": [
                {
                  "start": 712,
                  "end": 718,
                  "line_no": 28,
                  "col_no": 20
                }
              ]
            },
            {
              "file": "/path/src/AppBundle/Command/ClassifyForecastsCommand.php",
              "references": []
            },
            {
              "file": "/path/src/AppBundle/Command/CloseFailingFormalSpot.php",
              "references": []
            },
            {
              "file": "/path/src/AppBundle/Command/CloseOutdatedVotingBallot.php",
              "references": []
            },
            {
              "file": "/path/src/AppBundle/Command/CooptationRewardCommand.php",
              "references": []
            },
            {
              "file": "/path/src/AppBundle/Command/NoSpotPunisherCommand.php",
              "references": []
            },
            {
              "file": "/path/src/AppBundle/EventListener/Forecast/NotifyOnForecastListener.php",
              "references": []
            },
            {
              "file": "/path/src/AppBundle/EventListener/Forecast/NotifyForecasterAboutQualificationListener.php",
              "references": []
            }
          ]
        }
      }
    ]
  }
}
```

### PR DESCRIPTION
**Pull request by dantleech**
…s, fixes #581

### CODE REVIEW

File: lib/Extension/ClassMover/Rpc/ReferencesHandler.php [hunk 1]
```diff
@@ -151,14 +151,18 @@ public function handle(array $arguments)
...
         list($source, $references) = $this->performFindOrReplaceReferences($symbolContext, $filesystem);
 
         if (count($references) === 0) {
             return EchoResponse::fromMessage(self::MESSAGE_NO_REFERENCES_FOUND);
         }
 
+        $references = array_filter($references, function (array $referenceList) {
+            return false === empty($referenceList['references']);
+        });
+
```
Comment (dantleech) [inline lib/Extension/ClassMover/Rpc/ReferencesHandler.php]: Note we could allow a flag to be passed to find also risky references.
