### PR TITLE
Fix zend assertions

### LINKED ISSUE #1610: Question: Should zend.assertions = 1 work?
I've modified my setup resulting in `zend.assertions = 1` which breaks the setup. Calling the context menu results in:
```
Error detected while processing function phpactor#ContextMenu[1]..phpactor#rpc:
line   20:
E605: Exception not caught: Could not parse response from Phpactor: Vim(let):E474: Unidentified byte: Warning: assert(): assert($node instanceof AssignmentExpression) failed in /nix/store/im1r2bkl
9i73g0862w8s1ajpdd6h6sn9-vimplugin-phpactor-042c2f2733189118f8fe95a03b9701e43c81c98f/lib/WorseReflection/Core/Inference/Walker/PassThroughWalker.php on line 40^@Warning: assert(): assert($node ins
tanceof AssignmentExpression) failed in /nix/store/im1r2bkl9i73g0862w8s1ajpdd6h6sn9-vimplugin-phpactor-042c2f2733189118f8fe95a03b9701e43c81c98f/lib/WorseReflection/Core/Inference/Walker/PassThroug
hWalker.php on line 40^@Warning: assert(): assert($node instanceof AssignmentExpression) failed in /nix/store/im1r2bkl9i73g0862w8s1ajpdd6h6sn9-vimplugin-phpactor-042c2f2733189118f8fe95a03b9701e43c
81c98f/lib/WorseReflection/Core/Inference/Walker/PassThroughWalker.php on line 40^@Warning: assert(): assert($node instanceof AssignmentExpression) failed in /nix/store/im1r2bkl9i73g0862w8s1ajpdd6
h6sn9-vimplugin-phpactor-042c2f2733189118f8fe95
```

My old setup had `zend.assertions = -1` and reverting to `-1` removes the issue.

That's why I would kindly ask whether `zend.assertions = 1` should work?
https://www.php.net/manual/en/function.assert.php#function.assert.expectations documents the behaviour:

> 1: generate and execute code (development mode)
> 0: generate code but jump around it at runtime
> -1: do not generate code (production mode)

### PR DESCRIPTION
**Pull request by dantleech**
Fixes #1610

### CODE REVIEW

File: lib/Completion/Bridge/WorseReflection/Formatter/EnumCaseFormatter.php [hunk 1]
```diff
@@ -16,11 +15,7 @@ public function canFormat(object $object): bool
 
     public function format(ObjectFormatter $formatter, object $object): string
     {
-        assert($object instanceof ReflectionConstant);
-
-        if ($object->value() !== null) {
-            return sprintf('case %s = %s', $object->name(), json_encode($object->value()));
```
Comment (dantleech) [inline lib/Completion/Bridge/WorseReflection/Formatter/EnumCaseFormatter.php:22]: ReflectionEnumCase does not have `value()` so not sure how this ever worked
