### PR TITLE
Fix #1960 document highlight (regression?)

### LINKED ISSUE #1960: Document highlight does not work with recent changes
I switched back to 707e7d90 (before `constructor_property_promotion`) to make it working for me.

Can you confirm this bug? I get it on two separate environments.

### PR DESCRIPTION
**Pull request by dantleech**
Seems to work again after fixing the types... maybe an issue rather with PHP 8 fixes #1960

### CODE REVIEW

File: lib/Extension/LanguageServerReferenceFinder/Model/Highlighter.php [hunk 1]
```diff
@@ -45,6 +45,7 @@ public function highlightsFor(string $source, ByteOffset $offset): Highlights
         $lspHighlights = [];
 
         foreach ($highlights as $highlight) {
+            assert($highlight instanceof Highlight);
```
Comment (dantleech) [inline lib/Extension/LanguageServerReferenceFinder/Model/Highlighter.php:48]: added because there's a bug with type infernce #1961
