### PR TITLE
Significant improvements to Generics

### LINKED ISSUE #1875: Wrong generic
```php
<?php

/**
 * @template TKey
 * @implements Iterator<TKey, string>
 */
abstract class Test1 implements Iterator
{
}

/**
 * @extends Test<int>
 */
class Test2 extends Test1
{
    public function current(): mixed
    {
    }

    public function next(): void
    {
    }

    public function key(): mixed
    {
    }

    public function valid(): bool
    {
    }

    public function rewind(): void
    {
    }

}

/** @var Test2 $a */

foreach ($a as $value) {
    /** @psalm-trace $value -> string  */
    // phpactor: $value -> int
}
```

### PR DESCRIPTION
**Pull request by dantleech**
Fixes #1875 

This PR aims to refactor the generic type resolution to be much saner, and potentially also support arguments.

TODO:

- [x] Replace `GenericTypeResolver` with the new "map" resolver
- [ ] Investigate passing template variables to constructor/methods
- [ ] Include class-string<t> etc
- [x] Include stubs which are fundamental to WR (e.g. enum, iterators) to the WR by default, hardcoded locations

### CODE REVIEW

File: lib/WorseReflection/Bridge/TolerantParser/Reflection/ReflectionClass.php [hunk 1]
```diff
@@ -369,6 +370,11 @@ public function serviceLocator(): ServiceLocator
         return $this->serviceLocator;
     }
 
+    public function hierarchy(): ReflectionClassLikeCollection
+    {
+        return ReflectionClassLikeCollection::fromReflections((new ClassHierarchyResolver())->resolve($this));
```
Comment (dantleech) [inline lib/WorseReflection/Bridge/TolerantParser/Reflection/ReflectionClass.php:375]: this should be memoized

File: lib/WorseReflection/Bridge/TolerantParser/Reflection/ReflectionInterface.php [hunk 2]
```diff
@@ -158,6 +159,11 @@ public function docblock(): DocBlock
         );
     }
 
+    public function hierarchy(): ReflectionClassLikeCollection
+    {
+        return ReflectionClassLikeCollection::fromReflections((new ClassHierarchyResolver())->resolve($this));
```
Comment (dantleech) [inline lib/WorseReflection/Bridge/TolerantParser/Reflection/ReflectionInterface.php:164]: ditto

File: lib/WorseReflection/Core/Inference/GenericMapResolver.php [hunk 3]
```diff
@@ -0,0 +1,64 @@
...
+            return $templateMap;
+        }
+
+        foreach (array_merge(
+            $topReflection->docblock()->implements(),
+            $topReflection->docblock()->extends()
+        ) as $genericClass
+        ) {
+            if (!$genericClass instanceof GenericClassType) {
+                // todo: trigger a diagnostic?
```
Comment (dantleech) [inline lib/WorseReflection/Core/Inference/GenericMapResolver.php:41]: probably not in this PR, but would be good to have a diagnostic buffer where we can inject diagonstics for stuff like this

File: lib/WorseReflection/Tests/Inference/generics/gh-1530-example.test [hunk 4]
```diff
@@ -36,14 +36,4 @@ function foobar(Foos $foos) {
...
-
-    wrAssertType('Test\Collection<int,Test\Foo>', $foos->all());
-    wrAssertType('Test\Foo', $foos->all()->first());
-    wrAssertType('void', $foos->all()->first()->bar());
-    wrAssertType('Test\Collection<int,Test\Foo>', $foos->all()->filter(fn($foo)));
-
-    $filtered = $foos->all()->filter(fn($foo) => $foo);
-    foreach ($filtered as $foo) {
-        wrAssertType('void', $foo->bar());
-    }
```
Comment (dantleech) [inline lib/WorseReflection/Tests/Inference/generics/gh-1530-example.test:48]: add back
