### PR TITLE
Ensure errors bubble up and are caught in diangostic engine

### LINKED ISSUE #2364: Phpactor crashes shortly after opening Neovim
Hello!

The LS has started crashing shortly after opening Neovim  / starting the LS, not sure why.

```
[ERROR][2023-09-05 15:31:49] .../vim/lsp/rpc.lua:675	"rpc"	"/home/cwhite/.local/share/nvim/mason/bin/phpactor"	"stderr"	"\n"
[ERROR][2023-09-05 15:31:49] .../vim/lsp/rpc.lua:675	"rpc"	"/home/cwhite/.local/share/nvim/mason/bin/phpactor"	"stderr"	'In DiagnosticsParser.php line 46:\n                                                    \n  Could not decode expected PHPStan JSON string ""  \n                                                    \n\nlanguage-server [--address ADDRESS] [--no-loop]\n\n'
```

### PR DESCRIPTION
**Pull request by dantleech**
This PR fixes the error-handling regression introduced by the new (parallel) diagnostic engine and will also ensure that the user is notified if a linter/diagnostic provider crashes.

Fixes #2364

### CODE REVIEW

**Comment by dantleech** [comment]
depends on LS changes

File: lib/Extension/PhpCodeSniffer/Model/PhpCodeSnifferProcess.php [hunk 1]
```diff
@@ -138,7 +139,7 @@ private function runDiagnosticts(string $url, string $text, array $options = [])
                 && $exitCode !== self::EXIT_FOUND_NON_FIXABLE_ERRORS
                 && $exitCode !== self::EXIT_FILES_NEEDS_FIXING
             ) {
-                $this->logger->error(
+                throw new RuntimeException(
```
Comment (dantleech) [inline lib/Extension/PhpCodeSniffer/Model/PhpCodeSnifferProcess.php:142]: cc @bart-jaskulski the exceptions are now handled (was a regression with the last release that caused them not to be)
